// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpklbqyjfpawfmamzlqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwa2xicXlqZnBhd2ZtYW16bHFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODAyNjEsImV4cCI6MjA2NTE1NjI2MX0.Rf-5DRAMjdUWdRtxz9gZktNrhByZxdr5E29PmN8fmmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);